version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - mynetwork
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet mongodb://root:example@localhost:27017/admin
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - /app/node_modules
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017/zoocat?authSource=admin
      DB_NAME: zoocat
    depends_on:
      mongo:
        condition: service_healthy
    command: npm run dev
    networks:
      - mynetwork

networks:
  mynetwork:
